// Shared PDF layout primitives — every document/report type in lib/pdf/
// composes these instead of hand-rolling its own layout, same convention
// as the app's *Display.ts shared-constant files.

import { StyleSheet, Text, View } from "@react-pdf/renderer";
import { PDF_ACCENT, PDF_ACCENT_LINE, PDF_BORDER, PDF_MUTED, PDF_TEXT, brandName } from "@/lib/pdf/theme";

const styles = StyleSheet.create({
  letterhead: {
    borderBottomWidth: 2,
    borderBottomColor: PDF_ACCENT_LINE,
    paddingBottom: 12,
    marginBottom: 18,
  },
  brand: { fontSize: 10, fontWeight: 700, color: PDF_ACCENT, textTransform: "uppercase", letterSpacing: 1, marginBottom: 6 },
  title: { fontSize: 18, fontWeight: 700, color: PDF_TEXT },
  subtitle: { fontSize: 10, color: PDF_MUTED, marginTop: 2 },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 40,
    right: 40,
    borderTopWidth: 0.5,
    borderTopColor: PDF_BORDER,
    paddingTop: 6,
  },
  footerText: { fontSize: 8, color: PDF_MUTED },
  table: { width: "100%", marginTop: 12, marginBottom: 12 },
  headerRow: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: PDF_TEXT, paddingBottom: 4, marginBottom: 4 },
  row: { flexDirection: "row", borderBottomWidth: 0.5, borderBottomColor: PDF_BORDER, paddingVertical: 4 },
  headerCell: { fontSize: 9, fontWeight: 700, color: PDF_TEXT, textTransform: "uppercase" },
  cell: { fontSize: 9, color: PDF_TEXT },
});

export function Letterhead({ title, subtitle }: { title: string; subtitle?: string }) {
  return (
    <View style={styles.letterhead}>
      <Text style={styles.brand}>{brandName()}</Text>
      <Text style={styles.title}>{title}</Text>
      {subtitle ? <Text style={styles.subtitle}>{subtitle}</Text> : null}
    </View>
  );
}

export function PdfFooter() {
  return (
    <View style={styles.footer} fixed>
      <Text style={styles.footerText}>Generated by {brandName()} · times shown in Asia/Muscat</Text>
    </View>
  );
}

export type TableColumn = { header: string; width: string; align?: "left" | "right" | "center" };

export function ItemizedTable({ columns, rows }: { columns: TableColumn[]; rows: string[][] }) {
  return (
    <View style={styles.table}>
      <View style={styles.headerRow}>
        {columns.map((col, i) => (
          <Text key={i} style={[styles.headerCell, { width: col.width, textAlign: col.align ?? "left" }]}>
            {col.header}
          </Text>
        ))}
      </View>
      {rows.map((row, ri) => (
        <View key={ri} style={styles.row}>
          {row.map((cell, ci) => (
            <Text key={ci} style={[styles.cell, { width: columns[ci]?.width, textAlign: columns[ci]?.align ?? "left" }]}>
              {cell}
            </Text>
          ))}
        </View>
      ))}
    </View>
  );
}

export function LabeledValue({ label, value }: { label: string; value: string }) {
  return (
    <View style={{ marginBottom: 4 }}>
      <Text style={{ fontSize: 8, color: PDF_MUTED, textTransform: "uppercase" }}>{label}</Text>
      <Text style={{ fontSize: 10, color: PDF_TEXT }}>{value}</Text>
    </View>
  );
}
